# Generated by Django 4.2.4 on 2023-08-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiger',
            old_name='habitat',
            new_name='species',
        ),
    ]
